spring:
  application:
    name: price-hunter
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/price_hunter}
    username: ${DB_USERNAME:price_hunter}
    password: ${DB_PASSWORD:local_dev_only}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  error:
    include-message: never
